#!/bin/bash

home="/home/vcap"
#app_path="${home}/app"

echo "export PATH=${PATH}:${home}/deps/0/bin" > "${home}/exports.sh"
echo "alias terraform=tofu" >> "${home}/exports.sh"
echo "alias tf=tofu" >> "${home}/exports.sh"

AWS_ACCESS_KEY_ID=$(echo "${VCAP_SERVICES}" | jq '.s3[] | select(.name | contains("backup")) | .credentials.access_key_id')
AWS_SECRET_ACCESS_KEY=$(echo "${VCAP_SERVICES}" | jq '.s3[] | select(.name | contains("backup")) | .credentials.secret_access_key')
AWS_DEFAULT_REGION=$(echo "${VCAP_SERVICES}" | jq '.s3[] | select(.name | contains("backup")) | .credentials.region')
AWS_BUCKET=$(echo "${VCAP_SERVICES}" | jq '.s3[] | select(.name | contains("backup")) | .credentials.bucket')
AWS_ENDPOINT=$(echo "${VCAP_SERVICES}" | jq '.s3[] | select(.name | contains("backup")) | .credentials.endpoint')
AWS_FIPS_ENDPOINT=$(echo "${VCAP_SERVICES}" | jq '.s3[] | select(.name | contains("backup")) | .credentials.fips_endpoint')

if [ -n "${AWS_ACCESS_KEY_ID}" ]; then
  {
    echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
    echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
    echo "export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"
    echo "export AWS_BUCKET=${AWS_BUCKET}"
    echo "export AWS_ENDPOINT=${AWS_ENDPOINT}"
    echo "export AWS_FIPS_ENDPOINT=${AWS_FIPS_ENDPOINT}"
  } >> "${home}/exports.sh"
fi

MYSQL_CONN_STR=$(echo "${VCAP_SERVICES}" | jq '."aws-rds"[] | select(.plan | contains("mysql")) | .credentials.uri')
MYSQL_DATABASE=$(echo "${VCAP_SERVICES}" | jq '."aws-rds"[] | select(.plan | contains("mysql")) | .credentials.db_name')
MYSQL_HOST=$(echo "${VCAP_SERVICES}" | jq '."aws-rds"[] | select(.plan | contains("mysql")) | .credentials.host')
MYSQL_PASSWORD=$(echo "${VCAP_SERVICES}" | jq '."aws-rds"[] | select(.plan | contains("mysql")) | .credentials.password')
MYSQL_PORT=$(echo "${VCAP_SERVICES}" | jq '."aws-rds"[] | select(.plan | contains("mysql")) | .credentials.port')
MYSQL_USER=$(echo "${VCAP_SERVICES}" | jq '."aws-rds"[] | select(.plan | contains("mysql")) | .credentials.username')

if [ -n "${MYSQL_CONN_STR}" ]; then
  {
    echo "export MYSQL_CONN_STR=${MYSQL_CONN_STR}"
    echo "export MYSQL_DATABASE=${MYSQL_DATABASE}"
    echo "export MYSQL_HOST=${MYSQL_HOST}"
    echo "export MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    echo "export MYSQL_PORT=${MYSQL_PORT}"
    echo "export MYSQL_USER=${MYSQL_USER}"
  } >> "${home}/exports.sh"
fi

PG_CONN_STR=$(echo "${VCAP_SERVICES}" | jq '."aws-rds"[] | select(.plan | contains("psql")) | .credentials.uri')
PGDATABASE=$(echo "${VCAP_SERVICES}" | jq '."aws-rds"[] | select(.plan | contains("psql")) | .credentials.db_name')
PGHOST=$(echo "${VCAP_SERVICES}" | jq '."aws-rds"[] | select(.plan | contains("psql")) | .credentials.host')
PGPASSWORD=$(echo "${VCAP_SERVICES}" | jq '."aws-rds"[] | select(.plan | contains("psql")) | .credentials.password')
PGPORT=$(echo "${VCAP_SERVICES}" | jq '."aws-rds"[] | select(.plan | contains("psql")) | .credentials.port')
PGUSER=$(echo "${VCAP_SERVICES}" | jq '."aws-rds"[] | select(.plan | contains("psql")) | .credentials.username')

if [ -n "${PG_CONN_STR}" ]; then
  {
    echo "export PG_CONN_STR=${PG_CONN_STR}"
    echo "export PGDATABASE=${PGDATABASE}"
    echo "export PGHOST=${PGHOST}"
    echo "export PGPASSWORD=${PGPASSWORD}"
    echo "export PGPORT=${PGPORT}"
    echo "export PGUSER=${PGUSER}"
  } >> "${home}/exports.sh"
fi

sed -i '1s/^/source exports.sh\n/' "${home}/.bashrc"

while : ; do sleep 500 ; done

