rules:
  - id: "mysql-credentials"
    pattern: "mysql:\\/\\/[a-zA-Z0-9._%+-]+:[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+:[0-9]+\\/[a-zA-Z0-9._%+-]+"
    entropy: 3.0
  - id: "postgresql-credentials"
    pattern: "postgresql:\\/\\/[a-zA-Z0-9._%+-]+:[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+:[0-9]+\\/[a-zA-Z0-9._%+-]+"
    entropy: 3.0
