exclude: # exclude matching issues
  - message: Build directories
    paths:
      - rules.yml
      - .trufflehog3.yml
      - aws/**
      - *.png
      - *.zip
      - *.tar.gz
      - *.deb
      - *.so
      - *.so.*
      - fake_creds.txt
