exclude: # exclude matching issues
  - message: Build directories
    paths:
      - rules.yml
      - .trufflehog3.yml
      - aws/**
      - /home/runner/work/px-benefit-finder/px-benefit-finder/*.png
      - /home/runner/work/px-benefit-finder/px-benefit-finder/*.zip
      - /home/runner/work/px-benefit-finder/px-benefit-finder/*.tar.gz
      - /home/runner/work/px-benefit-finder/px-benefit-finder/*.deb
      - /home/runner/work/px-benefit-finder/px-benefit-finder/*.so
      - /home/runner/work/px-benefit-finder/px-benefit-finder/*.so.*
      - fake_creds.txt
      - truffleHogResults.json
      - bears-app/package.json
      - .circleci/config.yml
