#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

COMMIT_MESSAGE_FILE="$1"
COMMIT_MESSAGE="$(cat $1)"
COMMITPREFIX=$(git branch | grep '*' | sed 's/* //')

if [ ${#COMMIT_MESSAGE} = 0 ]
then
    exit 1
fi

echo "PXBF-$COMMITPREFIX"': '"$COMMIT_MESSAGE" > "$COMMIT_MESSAGE_FILE"
