#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
#!change directories and run items from .lintstagedrc
cd benefit-finder && npm run lint-staged

COMMIT_MESSAGE_FILE="$1"
COMMIT_MESSAGE=$(cat "$COMMIT_MESSAGE_FILE" | grep -v '^#')

COMMITPREFIX=$(git branch | grep '*' | sed 's/* //')

if [ ${#COMMIT_MESSAGE} = 0 ]
then
    exit 1
fi
echo "$COMMITPREFIX"': '"$COMMIT_MESSAGE" > "$COMMIT_MESSAGE_FILE"

exit 1
