---
name: Bug Report
description: Use this form to create a new Bug Report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Introduction

  - type: markdown
    attributes:
      value: >
        Bug Reports are used to report when something isn't working as-expected given the current state of the project.

  - type: markdown
    attributes:
      value: |
        ## Required fields

  - type: textarea
    id: expected
    attributes:
      label: What's expected
      description: "This is what you expected to happen."
    validations:
      required: true

  - type: textarea
    id: happened
    attributes:
      label: What happened
      description: "This is what you actually saw happen, particularly where it was different than what you expected."
    validations:
      required: true

  - type: textarea
    id: replicate
    attributes:
      label: How to replicate
      description: "Please tell us how we can replicate the problem. A step-by-step walk-through and screencapture is most helpful."
    validations:
      required: true
