---
name: Task
description: Use this form to create a new Tasks
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        ## Introduction

  - type: markdown
    attributes:
      value: >
        Tasks are associated with and/or make reference to
        User Stories. It's also common for the Definition of Done
        (DoD) from a User Story (the what) to be the starting point
        for Tasks (the how).

  - type: markdown
    attributes:
      value: |
        ## Required fields

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What work needs to be done.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Optional fields

  - type: textarea
    id: userstory
    attributes:
      label: User Story
      description: "If any User Stories (the what) are related to this Task (the how), please #mention the issue number(s) here"
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: "If any acceptance criteria are relevant to the execution of this task, please reference them here"
    validations:
      required: false
