---
name: Feature Request
description: Use this form to create a new feature request
labels: ["story"]
body:
  - type: markdown
    attributes:
      value: |
        ## Introduction

  - type: markdown
    attributes:
      value: >
        This form will guide you through creating a new feature request by proposing a [user story](https://www.agilealliance.org/glossary/user-stories/).

  - type: markdown
    attributes:
      value: >
        User stories capture **what** a user wants, not **how** they want
        it done.

  - type: markdown
    attributes:
      value: >
        User stories capture **what** a user wants, not **how** they want
        it done.

          - Describes a user’s goal (what), not a system interaction (how)
          - Is narrow, rather than shallow
          - Is potentially shippable -- it can be experienced, is
            understandable, a user could make use of it
          - Is option-enabling - doesn’t specify implementation details

  - type: markdown
    attributes:
      value: |
        ## Required fields

  - type: input
    id: persona
    attributes:
      label: User / Persona
      description: 'A user story is viewed from the perspective of a user or persona, such "content editor" or "user approaching retirement".'
      placeholder: "(who) As a..."
    validations:
      required: true
  - type: input
    id: reason
    attributes:
      label: Reason / Justification
      description: "Why the story should be completed."
      placeholder: "(why) so that...."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Optional fields
  - type: textarea
    id: ac
    attributes:
      label: Acceptance Criteria (AC)
      description: A list of criteria under which the team would consider this story complete; may include references to issues.
      value: "- [ ] "
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other Notes
      description: List any additional notes (e.g., resources, links, diagrams, etc.) that the team may find useful or helpful when working on this user story.
    validations:
      required: false
