<?php

/**
 * @file
 * Module contains functions related to usagov_bears_page.
 */

/**
 * Implements hook_theme().
 *
 * @return array
 */
function usagov_bears_page_theme() {
  $theme['page__bears_life_event'] = [
    'base hook' => 'page',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_page_alter().
 *
 * @param array &$suggestions
 * @param array $variables
 */
function usagov_bears_page_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node && $node->bundle() == "bears_life_event") {
    if (\Drupal::routeMatch()->getRouteName() == 'entity.node.canonical') {
      $suggestions[] = 'page__bears_life_event';
    }
  }
}

/**
 * Implements hook_page_attachments_alter().
 *
 * @param array $page
 */
function usagov_bears_page_page_attachments_alter(array &$page) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node && $node->bundle() == "bears_life_event") {
    if (\Drupal::routeMatch()->getRouteName() == 'entity.node.canonical') {
      $page['#attached']['library'][] = 'usagov_bears_page/bears_app';
    }
  }
}

/**
 * Implements hook_preprocess_page().
 *
 * @param $variables
 */
function usagov_bears_page_preprocess_page(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node && $node->bundle() == "bears_life_event") {
    if (\Drupal::routeMatch()->getRouteName() == 'entity.node.canonical') {
      $field_json_data_file = $node->get('field_json_data_file')->referencedEntities();
      $uri = $field_json_data_file[0]->getFileUri();
      $variables['json_data_file_path'] = \Drupal::service('file_url_generator')->generate($uri)->toString();
      $field_draft_json_data_file = $node->get('field_draft_json_data_file')->referencedEntities();
      $uri = $field_draft_json_data_file[0]->getFileUri();
      $variables['draft_json_data_file_path'] = \Drupal::service('file_url_generator')->generate($uri)->toString();
    }
  }
}
