name: Database nightly backup (main)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  backup-database-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install basic dependancies
        run: ./bin/cloudgov/deb-basic.deps.sh
      - name: Install AWSCLI
        run: ./bin/cloudgov/awscli-install.sh
      - name: Install MySQL Client
        run: ./bin/cloudgov/deb-mysql-client-install.sh
      - name: Install Cloudfoundry CLI
        run: ./bin/cloudgov/deb-cf-install.sh
      - name: Backup main database
        shell: bash
        env:
          CF_USER: '${{ secrets.CF_USER }}'
          CF_PASSWORD: '${{ secrets.CF_PASSWORD }}'
          CF_ORG: '${{ secrets.CF_ORG }}'
        run: |
          export TIMESTAMP=$(date --utc +%FT%TZ)
          export BACKUP_ENV=main
          source ./bin/cloudgov/cloud-gov-login.sh
          source ./bin/cloudgov/downsync-backup.sh
          source ./bin/cloudgov/upload-backup.sh