name: Production Links Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

permissions: read-all

defaults:
  run:
    working-directory: ./benefit-finder

jobs:
  install:
    name: cypress-run-prod-e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "./benefit-finder/package.json"

      - name: Cypress Run
        id: e2e
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          env: NODE_ENV=test
          config-file: cypress.prod.links.config.js
          working-directory: benefit-finder

      - name: Prod Artifact(s)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Prod cypress screenshots
          path: ./benefit-finder/cypress/screenshots


      - name: create github issue
        uses: dacbd/create-issue-action@main
        if: failure()
        with:
          token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          assignees: ${{ vars.TECH_LEAD }}, ${{ vars.CONTENT_LEAD }}
          title: |
            [${{ github.workflow }}] failed
          body: |
            ## Automated issue of produciton links test

            ## Failure Report:

            > [!IMPORTANT]
            > Details on failed run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
